version: "2.2"
services:
  nodea:
    environment:
      - SERVER_PORT=8080
    build: .
    ports:
      - "8080:8080"
  nodeb:
    environment:
      - SERVER_PORT=8081
    build: .
    ports:
      - "8081:8081"
  nodec:
    environment:
      - SERVER_PORT=8082
    build: .
    ports:
      - "8082:8082"