version: "2.2"
services:
  node1:
    environment:
      - SERVER_PORT=8080
      - IS_LEADER=true
    build: .
    container_name: Node1
    hostname: Node1
    ports:
      - "8080:8080"
    volumes:
      - db_data1:/var/lib/sqlite
  node2:
    environment:
      - SERVER_PORT=8081
      - IS_LEADER=false
    build: .
    container_name: Node2
    hostname: Node2
    ports:
      - "8081:8081"
    volumes:
      - db_data2:/var/lib/sqlite
  node3:
    environment:
      - SERVER_PORT=8082
      - IS_LEADER=false
    build: .
    container_name: Node3
    hostname: Node3
    ports:
      - "8082:8082"
    volumes:
      - db_data3:/var/lib/sqlite
  node4:
    environment:
      - SERVER_PORT=8083
      - IS_LEADER=false
    build: .
    container_name: Node4
    hostname: Node4
    ports:
      - "8083:8083"
    volumes:
      - db_data4:/var/lib/sqlite
  node5:
    environment:
      - SERVER_PORT=8084
      - IS_LEADER=false
    build: .
    container_name: Node5
    hostname: Node5
    ports:
      - "8084:8084"
    volumes:
      - db_data5:/var/lib/sqlite
volumes:
  db_data1:
    external: false
  db_data2:
    external: false
  db_data3:
    external: false
  db_data4:
    external: false
  db_data5:
    external: false
