version: "2.2"
services:
  nodea:
    environment:
      - SERVER_PORT=8080
      - IS_LEADER=true
    build: .
    ports:
      - "8080:8080"
    volumes:
      - db_data:/var/lib/sqlite
  nodeb:
    environment:
      - SERVER_PORT=8081
      - IS_LEADER=false
    build: .
    ports:
      - "8081:8081"
    volumes:
      - db_data:/var/lib/sqlite
  nodec:
    environment:
      - SERVER_PORT=8082
      - IS_LEADER=false
    build: .
    ports:
      - "8082:8082"
    volumes:
      - db_data:/var/lib/sqlite
volumes:
  db_data:
    external: true